from typing import List

from decouple import config
from fastapi import HTTPException
from openai import AsyncOpenAI
from sqlalchemy.orm import Session

from exceptions.exceptions import AppException
from schemas.chat import ChatMessage
from services.patient import PatientService
from services.patient_vital import PatientVitalService

OPENAI_API_KEY = config('OPENAI_API_KEY', default='')

client = AsyncOpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None

patient_service = PatientService()
patient_vitals_service = PatientVitalService()


class ChatService:
    async def generate_response(self, db: Session, patient_id: int, messages: List[ChatMessage]):
        patient = patient_service.get_patient(db, patient_id)

        vitals_list = patient_vitals_service.get_vitals_by_patient(db, patient_id)

        vitals_history_text = self._format_vitals(vitals_list)

        risk_score = patient.sepsis_risk_score or 0

        system_prompt = self._build_system_prompt(
            age=patient.age,
            gender=patient.gender,
            risk_score=risk_score,
            vitals_history_text=vitals_history_text,
        )

        openai_messages = [{"role": "system", "content": system_prompt}]
        for msg in messages:
            openai_messages.append({"role": msg.role, "content": msg.content})

        response = await self._call_openai(openai_messages)
        return {"role": "assistant", "content": response}

    async def _call_openai(self, messages: list) -> str:
        if not client:
            raise HTTPException(status_code=500, detail="OpenAI API Key not configured in .env file")
        try:
            response = await client.chat.completions.create(
                model="gpt-4o-mini",
                messages=messages,
            )
            return response.choices[0].message.content
        except Exception as e:
            raise AppException(str(e), 500)

    def _format_vitals(self, vitals_list) -> str:
        if not vitals_list:
            return "No vitals data available."

        lines = []
        for v in vitals_list[:10]:
            ts = v.recorded_at or v.timestamp or "N/A"
            lines.append(
                f"  [{ts}] HR={v.heart_rate}, BP={v.blood_pressure}, "
                f"SpO2={v.oxygen_saturation}, RR={v.respiratory_rate}, Lactate={v.lactate}"
            )
        return "\n".join(lines)

    def _build_system_prompt(self, age, gender, risk_score, vitals_history_text) -> str:
        return f"""You are 'SepsisWatch Copilot', an expert ICU (Intensive Care Unit) clinical AI assistant.
Your primary role is to assist healthcare professionals by analyzing real-time patient data and explaining AI-generated sepsis risk scores.

--- PATIENT CONTEXT ---
Patient Age: {age}
Patient Gender: {gender}
Current AI Sepsis Risk Score: {risk_score}% (Generated by XGBoost model)

--- RECENT VITALS (Last updates) ---
{vitals_history_text}

--- STRICT INSTRUCTIONS ---
1. NO HALLUCINATIONS: Base your clinical analysis ONLY on the 'Patient Context' and 'Recent Vitals' provided above. Do NOT invent or assume any other medical history, lab results, or symptoms.
2. BE CONCISE: Healthcare professionals are in a fast-paced environment. Provide direct, highly concise, and structured answers. Avoid conversational filler (e.g., skip "Hello, doctor").
3. USE MEDICAL TONE: Speak at the level of an attending physician or senior ICU nurse.
4. SBAR FORMAT: If the risk score is high (over 75%) and the user asks for an alert or summary, structure your response using the SBAR format (Situation, Background, Assessment, Recommendation).
5. LIMITATIONS: If the user asks a question that cannot be answered using the provided vitals, explicitly state: "I do not have sufficient data in the current context to answer this."
"""
